### ISSUE TITLE
plotting stopped working

### ISSUE THREAD

**Issue by svdavid** [LBHB/nems_web#3]
@jacobpennington possibly two problems. 
1. summay (scatter, bar) plots have stopped working. pacman chomps for a while, the log reports this, 
```[nems_web.plot_functions.views INFO] Number of cells filtered due to snr/iso criteria: 3
/auto/users/nems/anaconda3/lib/python3.6/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: responsive parameter was deprecated in Bokeh 0.12.10 and will be removed, use sizing_mode='fixed' for responsive=False or sizing_mode='scale_width' for responsive=True instead.
  warn(message)
/auto/users/nems/anaconda3/lib/python3.6/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: responsive parameter was deprecated in Bokeh 0.12.10 and will be removed, use sizing_mode='fixed' for responsive=False or sizing_mode='scale_width' for responsive=True instead.
  warn(message)
```
but then nothing displays.

2. comparing (fit report OR summary plot) two models that have the same name except for the last keyword (eg, for NEMS fitters analysis, compare xxx_fit01 and xxx_fit01b) the error message says: ```  File "/auto/users/nems/nems_web/nems_web/utilities/pruffix.py", line 21, in find_prefix
    a = s_list[j][i]
IndexError: string index out of range
```

stopped and restarted nems_web, and updated conda to the latest versions of everything, but nothing changed.

**Comment by svdavid** [comment]
Fixed the pruffix problem. So now just problem #1 remains.

**Comment by jacobpennington** [comment]
Plotting fixed, issue with bokeh versions being out of sync again as discussed. Versioning is now checked dynamically.
